name: hds_logistics_2022
channels:
  - conda-forge
dependencies:
  - contextily=1.2.0
  - folium=0.12.1
  - geopandas=0.10.2
  - geoplot=0.4.4
  - jupyterlab=3.2.4
  - jupyterlab-spellchecker=0.7.2
  - mapclassify=2.4.3
  - matplotlib=3.5.0
  - numpy=1.21.4
  - pandas=1.3.4
  - pip=21.3.1
  - pysal=2.5.0
  - python=3.8.8
  - scipy=1.7.3
  - seaborn=0.11.1