name: hds_logistics
channels:
  - conda-forge
dependencies:
  - contextily=1.4.0
  - folium=0.15.1
  - geopandas=0.14.1
  - geoplot=0.5.1
  - jupyterlab=4.0.9
  - jupyterlab-spellchecker=0.8.4
  - matplotlib=3.8.2
  - numpy=1.26.2
  - pandas=2.1.4
  - pip=23.3.1
  - pysal=23.7
  - python=3.10.13
  - scipy=1.11.4
  - seaborn=0.13.0
