name: hds_logistics
channels:
  - conda-forge
dependencies:
  - contextily=1.2.0
  - folium=0.13.0
  - geopandas=0.12.1
  - geoplot=0.5.1
  - jupyterlab=3.4.6
  - jupyterlab-spellchecker=0.7.2
  - mapclassify=2.4.3
  - matplotlib=3.5.3
  - numpy=1.23.2
  - pandas=1.4.4
  - pip=22.2.2
  - pysal=2.7.0
  - python=3.8.12
  - scipy=1.9.1
  - seaborn=0.11.1
